# Generated by Django 4.1.13 on 2024-02-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MFImageAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(help_text='Mediaflow ServerID', max_length=255)),
                ('server_key', models.CharField(help_text='Mediaflow ServerKey', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
