# Generated by Django 4.1.13 on 2024-03-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaflowimage', '0002_mfimage_customrendition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfimage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='mfimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='mfimage',
            name='uploaded_by_user',
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
        migrations.DeleteModel(
            name='MfImage',
        ),
    ]
